OFFICIAL_TECH_DOMAINS = [
    # Python Ecosystem
    "docs.python.org",
    "pypi.org",
    "docs.djangoproject.com",
    "flask.palletsprojects.com",
    "fastapi.tiangolo.com",
    "docs.celeryproject.org",
    "pytest.org",
    "numpy.org",
    "pandas.pydata.org",
    "scikit-learn.org",
    "pytorch.org",
    "tensorflow.org",
    "keras.io",
    "jupyter.org",
    "conda.io",
    "poetry.eustace.io",
    "pipenv.pypa.io",
    # JavaScript/Node.js Ecosystem
    "developer.mozilla.org",
    "nodejs.org",
    "npmjs.com",
    "yarnpkg.com",
    "reactjs.org",
    "nextjs.org",
    "vuejs.org",
    "nuxtjs.org",
    "angular.io",
    "svelte.dev",
    "expressjs.com",
    "nestjs.com",
    "socket.io",
    "webpack.js.org",
    "vitejs.dev",
    "rollupjs.org",
    "babeljs.io",
    "eslint.org",
    "prettier.io",
    "jestjs.io",
    "testing-library.com",
    "storybook.js.org",
    # Frontend/CSS Frameworks
    "tailwindcss.com",
    "getbootstrap.com",
    "bulma.io",
    "chakra-ui.com",
    "mui.com",
    "ant.design",
    "styled-components.com",
    "emotion.sh",
    # Mobile Development
    "reactnative.dev",
    "flutter.dev",
    "ionic.io",
    "cordova.apache.org",
    "expo.dev",
    "nativescript.org",
    # Backend Languages
    "golang.org",
    "go.dev",
    "rust-lang.org",
    "docs.rs",
    "crates.io",
    "php.net",
    "laravel.com",
    "symfony.com",
    "ruby-lang.org",
    "rubyonrails.org",
    "guides.rubyonrails.org",
    "docs.oracle.com",
    "spring.io",
    "docs.spring.io",
    "kotlinlang.org",
    "scala-lang.org",
    # Databases
    "postgresql.org",
    "dev.mysql.com",
    "docs.mongodb.com",
    "redis.io",
    "cassandra.apache.org",
    "neo4j.com",
    "elastic.co",
    "docs.influxdata.com",
    "sqlite.org",
    # Cloud Platforms
    "aws.amazon.com",
    "docs.aws.amazon.com",
    "cloud.google.com",
    "azure.microsoft.com",
    "docs.microsoft.com",
    "digitalocean.com",
    "linode.com",
    "vultr.com",
    "heroku.com",
    "netlify.com",
    "vercel.com",
    "firebase.google.com",
    "supabase.com",
    # DevOps & Infrastructure
    "docker.com",
    "docs.docker.com",
    "kubernetes.io",
    "helm.sh",
    "jenkins.io",
    "github.com",
    "docs.gitlab.com",
    "circleci.com",
    "travisci.org",
    "ansible.com",
    "docs.ansible.com",
    "terraform.io",
    "consul.io",
    "vault.hashicorp.com",
    "nomad.hashicorp.com",
    "grafana.com",
    "prometheus.io",
    # Version Control & Collaboration
    "git-scm.com",
    "github.com",
    "docs.github.com",
    "gitlab.com",
    "bitbucket.org",
    "atlassian.com",
    "jira.atlassian.com",
    "confluence.atlassian.com",
    # APIs & Protocols
    "openapi.tools",
    "swagger.io",
    "graphql.org",
    "apollographql.com",
    "grpc.io",
    "protobuf.dev",
    "oauth.net",
    "auth0.com",
    "okta.com",
    # Development Tools
    "code.visualstudio.com",
    "jetbrains.com",
    "vim.org",
    "neovim.io",
    "emacs.org",
    "sublimetext.com",
    "postman.com",
    "insomnia.rest",
    # Package Managers
    "brew.sh",
    "chocolatey.org",
    "winget.run",
    "snapcraft.io",
    "flathub.org",
    # Web Standards & Specifications
    "w3.org",
    "whatwg.org",
    "tc39.es",
    "ecma-international.org",
    "ietf.org",
    # Learning & Documentation
    "stackoverflow.com",
    "developer.mozilla.org",
    "dev.to",
    "medium.com",
    "hashnode.com",
    "freecodecamp.org",
    "codecademy.com",
    "coursera.org",
    "udemy.com",
    "pluralsight.com",
    "egghead.io",
    # Security
    "owasp.org",
    "cve.mitre.org",
    "snyk.io",
    "sonarqube.org",
    # Testing
    "selenium.dev",
    "cypress.io",
    "playwright.dev",
    "puppeteer.dev",
    # Design & UX
    "figma.com",
    "sketch.com",
    "adobe.com",
    "invisionapp.com",
    "zeplin.io",
    # CMS & E-commerce
    "wordpress.org",
    "drupal.org",
    "strapi.io",
    "shopify.dev",
    "magento.com",
    "woocommerce.com",
    # AI/ML
    "huggingface.co",
    "openai.com",
    "anthropic.com",
    "cohere.ai",
    "deepmind.com",
    "nvidia.com",
]


def get_official_domains():
    """
    Returns the list of official domains for technical searches.

    Returns:
        list: List of official domains
    """
    return OFFICIAL_TECH_DOMAINS
